### ISSUE TITLE
[Feature Request] LE Audio Support

### ISSUE THREAD

**Issue by zxzxwu** [google/bumble#341]
As https://github.com/google/bumble/pull/308 has been a little bit big, so I am going to list some roadmap here.

## Scope

The initial implementation will focus on the **Unicast Server** role defined in [Basic Audio Profile 2.1.1](https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/16212-BAP-html5/out/en/index-en.html#UUID-549cfb57-0ecd-923a-e722-d10cc7381929) due to its relative ease of implementation and critical role in testing. This initial phase will be limited to single-device (BR/EDR TWS-like) use cases. Following the successful completion of the single-instance implementation, we may expand the scope to include multi-instance support.

Unicast Client and Broadcast roles are not in the scope.

## Roadmap

There might be some PRs:

![image](https://github.com/google/bumble/assets/92432172/fffb0329-1156-422e-8f8c-244b5ad1ae86)

* [x] General
  - [x] LE Audio GATT definitions(BAP, MCP, CCP, CAP, CSIP, MICP, VCP)
    * https://github.com/google/bumble/pull/343
  - [x] CIS HCI packet definititions
    * https://github.com/google/bumble/pull/333
* [x] CSIP/CAP
  - [x] CSIS - Characteristics with plaintext SIRK
    * https://github.com/google/bumble/pull/350
  - [x] CAS
  - [x] [Optional] CSIS - RSI generation
  - [x] [Optional] CSIS - Encrypted SIRK
* [x] HCI / Host
  - [x] CIS integration
    * https://github.com/google/bumble/pull/344
* [x] BAP
  - [x] PACS support
    * https://github.com/google/bumble/pull/356
  - [x] ASCS & Sink ASE
    * https://github.com/google/bumble/pull/359
  - [x] Source ASE
  - [x] LC3 codec integration(coop with liblc3)
* [ ] [Optional] EATT(Enhanced ATT)

By the end of 2023, I think at least General, CAP and CSIP are not too difficult to complete.

BAP might have some progress in the December, but CIS integration will take a longer time. If there cannot be an overall solution, at least we can provide an example Unicast server built on a naive structure.

**Comment by zxzxwu** [comment]
https://github.com/google/bumble/pull/343 for [1]

**Comment by barbibulle** [comment]
Great plan. I'm all for splitting the effort into incremental (and/or parallel) steps. As long as we make it clear that the entire LE audio support will be in flux for a while, and highly experimental (the APIs defined along the way are likely to change as we build this up).

**Comment by zxzxwu** [comment]
It seems like CSIP/CAP might not be necessary when only single device is present?
